export const alphabet = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
];

export type Options = {
    [key: string]: string[];
};

export const options: Options = {
    animals: ["DOG", "CAT", "SNAKE", "RABBIT", "ELEPHANT", "HORSE", "LION"],
    cities: [
        "LONDON",
        "PARIS",
        "MADRID",
        "MUNICH",
        "DUBLIN",
        "LISBON",
        "WELLINGTON",
    ],
    countries: [
        "ENGLAND",
        "FRANCE",
        "SPAIN",
        "IRELAND",
        "PORTUGAL",
        "INDIA",
        "RUSSIA",
    ],
    pokemon: [
        "PIKACHU",
        "EKANS",
        "WEEDLE",
        "BULBASAUR",
        "CHARMANDER",
        "SQUIRTLE",
        "NIDORAN",
        "ODDISH",
        "GROWLITHE",
    ],
};
